#!/bin/sh
#
# 2299-docker-restart
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }

if [ -f /usr/bin/docker ]; then
  sudo salt-call state.sls run.docker-restart
fi
