#!/bin/bash
#
# 0000-update-kernel
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }

# Update the kernel before doing much of anything else as docker, if nothing
# else, pukes on a kernel upgrade after being installed and having containers
# running

if [ $(uname -r | cut -b1) -lt 4 ] ; then
  #install_package "linux-image-amd64" backports force

  # Temporarily copy down the 4.4.0 kernel as there is a overlayfs bug between 4.4.1 and 4.5.2 and backports is currently on 4.5.0.
  file1="linux-image-4.4.0-0.bpo.1-amd64_4.4.6-1~bpo8+1_amd64.deb"
  file2="linux-image-amd64_4.4+71~bpo8+1_amd64.deb"

  gsutil cp gs://naiadsys/$file1 /tmp/$file1 || fatal $? "Failed to copy: $file1"
  gsutil cp gs://naiadsys/$file2 /tmp/$file2 || fatal $? "Failed to copy: $file2"

  dpkg -i /tmp/$file1 || fatal $? "Failed to dpkg: $file1"
  dpkg -i /tmp/$file2 || fatal $? "Failed to dpkg: $file2"

  sudo reboot
fi
