#!/bin/sh
#
# 1000-remove-metadata
#
# Update the GCE metadata to remove any of the following keys that may exist or not:
#   ezvm-updates
#   startup-script
#   startup-script-url
#
# If we have previously set startup-script-url to be the ezvm-bootstrap,
# then that means on every reboot we'll bootstrap again, which is probably
# not what you want.  So run this to unset it so reboot works the way it
# normally does, without a rerun of the bootstrap.
#
# Any existing setting for startup-script (embedded script) is also considered
# to be desired only once, and is removed.
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }

zone_ident=$(get_metadata "zone")
r=$?
case $r in
    22) ;; # This is a 404 error, as in the zone doesn't exist; no problem.
    0) ;; # Success we got the zone
    *) fatal $r "Error querying zone (code=$r)" ;;
esac
zone=$(echo "$zone_ident" | sed -e 's,.*/zones/,,' -e 's,/.*,,')

instance=$(hostname)
cmd="gcloud compute instances remove-metadata $instance --zone $zone --keys startup-script-url,startup-script,ezvm-updates"
echo "$cmd"
sudo $cmd || fatal $? "Failed to remove metadata on instance=$instance"
