#!/bin/sh
#
# 1099-install-salt-config
#
# If a custon salt configuration exists, install it.
#
# Do this before the salt master or minion is installed.  The install won't overwrite
# an existing config, and this prevents us having to restart after installing.
#

MINION_CONFIG="$(dirname "$0")/../../files/etc-salt-minion"

[ -d /etc/salt ] || sudo mkdir /etc/salt || exit $?

if [ -f "$MINION_CONFIG" ] ; then
  echo "Installing custom salt minion config"
  sudo cp "$MINION_CONFIG" /etc/salt/minion || exit $?
fi
