#!/bin/sh
#
# 1099-install-salt-config
#
# If a custon salt configuration exists, install it.
#

MINION_CONFIG="$(dirname "$0")/../../files/etc-salt-minion"

[ -d /etc/salt ] || sudo mkdir /etc/salt || exit $?

if [ -f "$MINION_CONFIG" ] ; then
  echo "Installing custom salt minion config"
  sudo cp "$MINION_CONFIG" /etc/salt/minion || exit $?
  sudo systemctl restart salt-minion.service || exit $?
fi
