#!/bin/sh
#
# 2000-install-salt-minion
#
# Having already updated apt so it will install salt packages, we now install the
# dependencies and the salt-minion.
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }
. "$(dirname "$0")/../../salt-lib.sh" || { echo "Cannot include ../../salt-lib.sh" 1>&2; exit 1; }

MINION_FLAGS=""

install_salt "$MINION_FLAGS"

fix_salt_init_path "salt-minion"
