#!/bin/bash
#
# 1002-saltstack-apt-sources
#
# This script installs the saltstack PGP key and configures apt/sources.list.d
# so that we can install packages from debian.saltstack.com
#
# When ezvm executes this script, the cwd is the local/update dir (e.g. ../)
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }

tmp="$(mktemp -t ezvm.XXXXXX)"

# First thing, import the saltstack PGP key
if ! sudo apt-key list | grep 'packaging@saltstack.com' > /dev/null; then
    cat ../files/saltstack.gpg | sudo apt-key add - || fatal $? "Cannot add saltstack.gpg to apt"
    # Remember that we changed something
    echo "saltstack.gpg" >> "$BUILD_DIR/apt.changes"
fi

# Add jessie sources as an option
if [ ! -f /etc/apt/sources.list.d/saltstack.list ]; then
    echo "deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main" > "$tmp"
    sudo install -o root -m 0644 "$tmp" /etc/apt/sources.list.d/saltstack.list || fatal $? "Cannot install saltstack apt sources"
    # Remember that we changed something
    echo "saltstack sources" >> "$BUILD_DIR/apt.changes"
fi

rm -f "$tmp"
