#!/bin/sh
#
# 2097-salt-deps
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }

install_package "libssl-dev"
install_package "libssl-dev"
install_package "libffi-dev"
install_package "python-dev"
install_package "python-gnupg"

sudo pip install --upgrade setupext-pip
sudo pip install --upgrade cryptography
sudo pip install --upgrade six
sudo pip install --upgrade pyOpenSSL
