#!/bin/sh
#
# 2000-install-salt-master
#
# Having already updated apt so it will install salt packages, we now install the
# dependencies and the salt-master.
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }
. "$(dirname "$0")/../../salt-lib.sh" || { echo "Cannot include ../../salt-lib.sh" 1>&2; exit 1; }

MASTER_FLAGS="-M"

install_salt "$MASTER_FLAGS"

fix_salt_init_path "salt-master"
fix_salt_init_path "salt-minion"  # Running a minion on the master as well
