#!/bin/sh
#
# 2000-install-salt-master
#
# Having already updated apt so it will install salt packages, we now install the
# dependencies and the salt-master.
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }


# Note: salt-master requires the backports version of python-zmq
install_package "python-zmq" "backports"

# Install the master itself
install_package "salt-master"
