#!/bin/sh
#
# 2059-reinstall-salt-config
#
# Salt bootstrap is broken, overwrites our configs.
# Reinstall our config and restart salt master and minion.
#

MASTER_CONFIG="$(dirname "$0")/../../files/etc-salt-master"
MINION_CONFIG="$(dirname "$0")/../../files/etc-salt-minion"

[ -d /etc/salt ] || sudo mkdir /etc/salt || exit $?

if [ -f "$MASTER_CONFIG" ] ; then
  echo "Reinstalling custom salt master config"
  sudo cp "$MASTER_CONFIG" /etc/salt/master || exit $?
  sudo /etc/init.d/salt-master restart || exit $?
fi

if [ -f "$MINION_CONFIG" ] ; then
  echo "Reinstalling custom salt minion config"
  sudo cp "$MINION_CONFIG" /etc/salt/minion || exit $?
  sudo /etc/init.d/salt-minion restart || exit $?
fi
