#!/bin/sh
#
# 2099-install-salt-config
#
# If a custon salt configuration exists, install it and restart.
#

MASTER_CONFIG="$(dirname "$0")/../../files/etc-salt-master"
MINION_CONFIG="$(dirname "$0")/../../files/etc-salt-minion"

if [ -f "$MASTER_CONFIG" ] ; then
  exec sudo cp "$MASTER_CONFIG" /etc/salt/master
  exec sudo /etc/init.d/salt-master restart
fi

if [ -f "$MINION_CONFIG" ] ; then
  exec sudo cp "$MINION_CONFIG" /etc/salt/minion
  exec sudo /etc/init.d/salt-minion restart
fi
