#!/bin/sh
#
# 2500-install-salt-config
#
# If a custon salt configuration exists, install it.
#

MASTER_CONFIG="$(dirname "$0")/../../files/etc-salt-master"
MINION_CONFIG="$(dirname "$0")/../../files/etc-salt-minion"

[ -d /etc/salt ] || sudo mkdir /etc/salt || exit $?

if [ -f "$MASTER_CONFIG" ] ; then
  echo "Installing custom salt master config"
  sudo cp "$MASTER_CONFIG" /etc/salt/master || exit $?
  sudo systemctl restart salt-master.service || exit $?
fi

if [ -f "$MINION_CONFIG" ] ; then
  echo "Installing custom salt minion config"
  sudo cp "$MINION_CONFIG" /etc/salt/minion || exit $?
  HOSTNAME=$(hostname -s) && perl -0pi -e "s/\n#id:\n/\nid: $HOSTNAME\n/" /etc/salt/minion
  sudo systemctl restart salt-minion.service || exit $?
fi

# Give the master and minion a few seconds to spin up before continuing
sleep 5
