#!/bin/sh
#
# 3000-upgrade-salt-master
#
# Now that the salt master is installed, upgrade it to get point releases.
#

. "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }

salt-call pkg.install salt-master refresh=True
