#!/bin/sh
#
# 0001-update-gcloud-components
#
# Don't know why, but google's own images don't have updated gcloud components
# on them.  So we'll explicitly update.
#

. "$(dirname "$0")/../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }


sudo gcloud components update -q || fatal $? "Failed to update gcloud components"
